org: rosborne132
app: shopping-list-app
service: shopping-list-app

myApp:
    component: 'serverless-next.js'
    inputs:
        region: us-west-2
        domain: ['www', 'shopping-list-app.com']
        policy: 'arn:aws:iam::280138148799:policy/user-items-app-db-policy'

database:
    component: '@serverless/aws-dynamodb'
    inputs:
        name: user-items-prod
        region: us-west-2
        attributeDefinitions:
            - AttributeName: itemId
              AttributeType: S
            - AttributeName: username
              AttributeType: S
        keySchema:
            - AttributeName: itemId
              KeyType: HASH
            - AttributeName: username
              KeyType: RANGE
        billingMode: PROVISIONED
        globalSecondaryIndexes:
            - IndexName: username-index
              KeySchema:
                  - AttributeName: username
                    KeyType: HASH
              Projection:
                  ProjectionType: ALL
